#!/usr/bin/env python3
import json
from pathlib import Path
R=Path(__file__).resolve().parent
U={'01I':'https://www.senate.mo.gov/26info/pdf-bill/intro/SB1012.pdf','02C':'https://www.senate.mo.gov/26info/pdf-bill/comm/SB1012.pdf','10F':'https://www.senate.mo.gov/BillTracking/Bills/BillInformation?amendmentId=309&handler=AmendmentPdf&year=2026','16F':'https://www.senate.mo.gov/BillTracking/Bills/BillInformation?amendmentId=631&handler=AmendmentPdf&year=2026','16P':'https://www.senate.mo.gov/26info/pdf-bill/perf/SB1012.pdf'}
p=R/'source_catalog.json'; c=json.loads(p.read_text()); ids={x['id'] for x in c['sources']}
S=[('mo-sb1012-01I','Missouri Senate — SB 1012 introduced, 5687S.01I','introduced_bill','01I','Official introduced text.'),('mo-sb1012-02C','Missouri Senate — SCS SB 1012, 5687S.02C','committee_substitute','02C','Official Senate Committee Substitute.'),('mo-sb1012-10F','Missouri Senate — withdrawn SS for SCS SB 1012, 5687S.10F','amendment','10F','Official first Senate Substitute; action history records withdrawal 30 Apr 2026.'),('mo-sb1012-16F','Missouri Senate — SS#2 for SCS SB 1012, 5687S.16F','amendment','16F','Official second Senate Substitute; adopted as amended 30 Apr 2026.'),('mo-sb1012-16P','Missouri Senate — perfected SS#2 SCS SB 1012, 5687S.16P','perfected_bill','16P','Official perfected text.')]
for sid,label,kind,k,note in S:
 if sid not in ids:c['sources'].append({'id':sid,'label':label,'kind':kind,'url':U[k],'jurisdiction':'MO','note':note})
p.write_text(json.dumps(c,indent=2,ensure_ascii=False)+'\n')
p=R/'claim_evidence.json'; e=json.loads(p.read_text()); r=next(x for x in e['records'] if x['record_id']=='mo-sb1012-2026'); status=next(x for x in r['claims'] if x['claim'].get('field')=='status.stage')
r['claims']=[status,
{'claim':{'field':'provisions','version_id':'mo-sb1012-2026--5687S.01I','provision':'denies_legal_personhood'},'value':False,'assessment':'checked_absent','mode':'direct','supports':[{'source_ref':'mo-sb1012-01I','locator':'Full introduced text; chapters 130 and 573 only; no § 1.2045 or legal-personhood provision'}]},
{'claim':{'field':'provisions','version_id':'mo-sb1012-2026--5687S.02C','provision':'denies_legal_personhood'},'value':True,'assessment':'present','mode':'direct','supports':[{'source_ref':'mo-sb1012-02C','locator':'§ 1.2045.4: government entity shall not grant an AI system legal personhood'}]},
{'claim':{'field':'provisions','version_id':'mo-sb1012-2026--5687S.16P','provision':'denies_legal_personhood'},'value':True,'assessment':'present','mode':'direct','supports':[{'source_ref':'mo-sb1012-16P','locator':'§ 1.2045.4: government entity shall not grant an AI system legal personhood'}]},
{'claim':{'field':'provisions','version_id':'mo-sb1012-2026--5687S.16P','provision':'restricts_chatbot_claims'},'value':False,'assessment':'checked_absent','mode':'direct','supports':[{'source_ref':'mo-sb1012-16P','locator':'Full § 1.2058 reviewed: operator disclosure/notification and safety duties, but no prohibition on what the chatbot may claim about sentience, consciousness, or humanness'}]},
{'claim':{'field':'provision_change','from_version_id':'mo-sb1012-2026--5687S.01I','to_version_id':'mo-sb1012-2026--5687S.02C','provision':'denies_legal_personhood'},'value':'added in committee substitute','mode':'direct','supports':[{'source_ref':'mo-sb1012-01I','locator':'Full introduced text: no § 1.2045'},{'source_ref':'mo-sb1012-02C','locator':'§ 1.2045.4 personhood prohibition'}]},
{'claim':{'field':'provision_change','from_version_id':'mo-sb1012-2026--5687S.02C','to_version_id':'mo-sb1012-2026--5687S.16P','provision':'addresses_corporate_veil'},'value':'detailed veil-piercing test removed; generic corporate-law anti-evasion sentence retained','mode':'direct','supports':[{'source_ref':'mo-sb1012-02C','locator':'§ 1.2045.13 expressly authorizes piercing the corporate veil on listed conditions'},{'source_ref':'mo-sb1012-16P','locator':'§ 1.2045.12 contains only a corporate-law liability-protection anti-evasion sentence; no veil-piercing test'}]},
{'claim':{'field':'provision_change','from_version_id':'mo-sb1012-2026--5687S.02C','to_version_id':'mo-sb1012-2026--5687S.16P','provision':'companion_chatbot_section'},'value':'§ 1.2058 added','mode':'direct','supports':[{'source_ref':'mo-sb1012-02C','locator':'Section A lists §§ 1.2045, 130.165, 573.120'},{'source_ref':'mo-sb1012-16P','locator':'Section A lists §§ 1.2045, 1.2058, 130.165; § 1.2058 creates companion-chatbot duties and civil action'}]}]
p.write_text(json.dumps(e,indent=2,ensure_ascii=False)+'\n');print('G3 claim provenance applied')
