"""One-off seed of registry/bills.json from Smith, Caviola & Alexander (2026).
After this runs, bills.json is the hand-edited source of truth. Do not re-run."""
import json

PROV = "Seeded from Smith, Caviola & Alexander (2026), Table 1, Figure 2 and 'Laws and Bills Cited'"
ASOF = "2026-05-12"   # the paper's own 'as of' date

def B(**k):
    d = dict(
        jurisdiction={"country": "US", "level": "state"},
        companion_group=None, codified_at=None, derived_from=None,
        definitional_anchor="unknown", augmented_human_exposure="unclear",
        affects_algorithmic_entity_formation="not_analysed", corporate_carve_out="unknown",
        constitutional_exposure=[], sponsors=[], versions=[], key_clause=None,
        evidence_refs=[], provenance=PROV, verification_status="seeded_unverified",
        last_verified=None, notes="",
    )
    d.update(k)
    d["jurisdiction"] = {"country": "US", "level": "state", "state": k["_state"]}
    del d["_state"]
    return d

LS = "legiscan.com"
bills = [

# ---------- Family A ----------
B(id="id-hb720-2022", _state="ID", bill_number="HB 720", chamber="house",
  session={"legislature": "68th", "session": "2nd Reg. Sess.", "year_introduced": 2022},
  status={"stage": "enacted", "as_of": ASOF, "source_url": "https://legislature.idaho.gov/sessioninfo/2022/legislation/H0720/"},
  codified_at="Idaho Code § 5-346",
  family="A", technique="standalone_provision",
  provisions=["denies_legal_personhood", "covers_non_ai_entities"],
  definitional_anchor="none", augmented_human_exposure="unanchored",
  affects_algorithmic_entity_formation="untested", corporate_carve_out="express_saving_clause",
  constitutional_exposure=[{"amendments": ["1st","5th","8th","9th","10th","14th"], "claimed_by": "jaynes2024"}],
  sponsors=[{"name": "Tammy Nichols", "party": "R", "role": "primary"}],
  key_clause={"text": "...environmental elements, artificial intelligence, nonhuman animals, and inanimate objects shall not be granted personhood in the State of Idaho.", "source": "HB 720 (2022)"},
  evidence_refs=["boone2022", "iff2022", "nichols2025a", "nichols2025b"],
  versions=[{"label": "enacted", "date": "2022", "source_url": "https://legislature.idaho.gov/statutesrules/idstat/title5/t5ch3/sect5-346/"}],
  sources={"primary": ["https://legislature.idaho.gov/sessioninfo/2022/legislation/H0720/",
                       "https://legislature.idaho.gov/statutesrules/idstat/title5/t5ch3/sect5-346/"],
           "tracker": [f"https://{LS}/ID/bill/H0720/2022"]},
  notes="First in nation. Covers AI, nature, animals and inanimate objects. Saving clause preserves personhood of municipalities, corporations and other entities recognised before the effective date. codified_at from Jaynes (2024), not from the paper."),

B(id="nd-hb1361-2023", _state="ND", bill_number="HB 1361", chamber="house",
  session={"legislature": "68th", "session": "Reg. Sess.", "year_introduced": 2023},
  status={"stage": "enacted", "as_of": ASOF, "source_url": "https://ndlegis.gov/assembly/68-2023/regular/bill-overview/bo1361.html"},
  family="A", derived_from="id-hb720-2022", technique="amends_general_person_definition",
  provisions=["denies_legal_personhood", "covers_non_ai_entities"],
  definitional_anchor="unknown", corporate_carve_out="unknown",
  sponsors=[{"name": "Cole Christensen", "party": "R", "role": "sponsor"},
            {"name": "Jeff Hoverson", "party": "R", "role": "sponsor"}],
  evidence_refs=["ndleg2023", "ndcan2023", "ndfa_nd", "dodson2023"],
  versions=[{"label": "enacted", "date": "2023", "source_url": "https://ndlegis.gov/assembly/68-2023/regular/bill-overview/bo1361.html"}],
  sources={"primary": ["https://ndlegis.gov/assembly/68-2023/regular/bill-overview/bo1361.html"],
           "tracker": [f"https://{LS}/ND/bill/HB1361/2023"]},
  notes="Near-identical to Idaho HB 720 but amends the ND Century Code definition of 'person', so it changes personhood across the whole code. Amended after Catholic Conference testimony raised juridical-personhood concerns."),

B(id="ok-hb3546-2026", _state="OK", bill_number="HB 3546", chamber="house",
  session={"legislature": "60th", "session": "2nd Reg. Sess.", "year_introduced": 2026},
  status={"stage": "passed_one_chamber", "as_of": ASOF, "source_url": "https://www.oklegislature.gov/BillInfo.aspx?Bill=hb3546&Session=2600"},
  family="A", derived_from="id-hb720-2022", technique="standalone_provision",
  provisions=["denies_legal_personhood", "covers_non_ai_entities"],
  sponsors=[{"name": "Cody Maynard", "party": "R", "role": "sponsor"}],
  evidence_refs=["maynard_nd"],
  sources={"primary": ["https://www.oklegislature.gov/BillInfo.aspx?Bill=hb3546&Session=2600"],
           "tracker": [f"https://{LS}/OK/bill/HB3546/2026"]},
  notes="Idaho template, adding 'association' and 'nonprofit organization' to the entities that expressly retain personhood. Passed the House 94-2 in March 2026 (source: media, verify)."),

# ---------- Family B ----------
B(id="ut-hb249-2024", _state="UT", bill_number="HB 249", chamber="house",
  session={"legislature": None, "session": "2024 Gen. Sess.", "year_introduced": 2024},
  status={"stage": "enacted", "as_of": ASOF, "source_url": "https://le.utah.gov/~2024/bills/static/HB0249.html"},
  family="B", derived_from="id-hb720-2022", technique="standalone_provision",
  provisions=["denies_legal_personhood", "covers_non_ai_entities"],
  definitional_anchor="taxonomic", augmented_human_exposure="anchored",
  affects_algorithmic_entity_formation="bars", corporate_carve_out="prospective_only",
  constitutional_exposure=[{"amendments": ["1st","5th","8th","9th","10th","14th"], "claimed_by": "jaynes2024"}],
  sponsors=[{"name": "Walt Brooks", "party": "R", "role": "primary"}],
  key_clause={"text": "a government entity may not grant legal personhood to, nor recognize legal personhood in: (1) artificial intelligence; (2) an inanimate object; (3) a body of water; (4) land; (5) real property; (6) atmospheric gases; (7) an astronomical object; (8) weather; (9) a plant; (10) a nonhuman animal; or (11) any other member of a taxonomic domain that is not a human being", "source": "HB 249 (2024)"},
  evidence_refs=["ut_house2024", "ut_senate2024", "roche2024", "romero2024", "williams2024",
                 "earthlaw2024", "sogsl_nd", "nhrp2025", "banutah_complaint", "banutah_dismissal"],
  versions=[{"label": "enacted", "date": "2024", "source_url": "https://le.utah.gov/~2024/bills/static/HB0249.html"}],
  sources={"primary": ["https://le.utah.gov/~2024/bills/static/HB0249.html"],
           "tracker": [f"https://{LS}/UT/bill/HB0249/2024"]},
  notes="Eleven enumerated categories plus formal definitions. Bars only the granting of NEW personhood, so needs no corporate saving clause. Triggered Ban v. Utah (NhRP), dismissed May 2025. affects_algorithmic_entity_formation per Jaynes (2024) on the zero-member LLC."),

B(id="sc-hb3796-2025", _state="SC", bill_number="HB 3796", chamber="house",
  session={"legislature": "126th", "session": "1st Reg. Sess.", "year_introduced": 2025},
  status={"stage": "in_committee", "as_of": ASOF, "source_url": "https://www.scstatehouse.gov/billsearch.php?billnumbers=3796&session=126&summary=B"},
  family="B", derived_from="ut-hb249-2024", technique="standalone_provision",
  provisions=["denies_legal_personhood", "covers_non_ai_entities"],
  definitional_anchor="taxonomic",
  sources={"primary": ["https://www.scstatehouse.gov/billsearch.php?billnumbers=3796&session=126&summary=B"],
           "tracker": [f"https://{LS}/SC/bill/H3796/2025"]},
  notes="Reproduces Utah HB 249 nearly verbatim."),

B(id="wa-hb2029-2025", _state="WA", bill_number="HB 2029", chamber="house",
  session={"legislature": "69th", "session": "Reg. Sess.", "year_introduced": 2025},
  status={"stage": "failed", "as_of": ASOF, "source_url": "https://app.leg.wa.gov/billsummary?BillNumber=2029&Year=2025&Initiative=false"},
  family="B", derived_from="ut-hb249-2024", technique="standalone_provision",
  provisions=["denies_legal_personhood", "covers_non_ai_entities"],
  definitional_anchor="taxonomic",
  sources={"primary": ["https://app.leg.wa.gov/billsummary?BillNumber=2029&Year=2025&Initiative=false"],
           "tracker": [f"https://{LS}/WA/bill/HB2029/2025"]},
  notes="Reproduces Utah HB 249 nearly verbatim. First liberal-leaning / tech state to consider an Exclusion Bill."),

# ---------- Family C ----------
B(id="mo-hb1462-2025", _state="MO", bill_number="HB 1462", chamber="house",
  session={"legislature": "103rd", "session": "1st Reg. Sess.", "year_introduced": 2025},
  status={"stage": "failed", "as_of": ASOF, "source_url": "https://house.mo.gov/Bill.aspx?bill=HB1462&year=2025&code=R"},
  family="C", technique="standalone_provision",
  provisions=["denies_legal_personhood", "declares_non_sentient", "assigns_liability_to_humans"],
  key_clause={"text": "non-sentient entities [which shall not] be considered to possess consciousness, self-awareness, or similar traits of living beings", "source": "HB 1462 (2025)"},
  sources={"primary": ["https://house.mo.gov/Bill.aspx?bill=HB1462&year=2025&code=R"],
           "tracker": [f"https://{LS}/MO/bill/HB1462/2025"]},
  notes="Originator of Family C. First bill to declare AI non-conscious. Enumerates denied statuses: marriage, property ownership, responsibility for harms, liability, managerial positions in corporate entities. Died in committee 2025, reintroduced 2026 as four bills."),

B(id="oh-hb469-2025", _state="OH", bill_number="HB 469", chamber="house",
  session={"legislature": "136th", "session": "Reg. Sess.", "year_introduced": 2025},
  status={"stage": "in_committee", "as_of": ASOF, "source_url": "https://www.legislature.ohio.gov/legislation/136/hb469"},
  family="C", derived_from="mo-hb1462-2025", technique="standalone_provision",
  provisions=["denies_legal_personhood", "declares_non_sentient", "assigns_liability_to_humans"],
  augmented_human_exposure="unanchored",
  constitutional_exposure=[{"amendments": ["1st"], "claimed_by": "alexander_simon2025"}],
  sponsors=[{"name": "Thaddeus Claggett", "party": "R", "role": "primary"}],
  key_clause={"text": "no AI system shall be considered to possess consciousness, self-awareness, or similar traits of living beings", "source": "HB 469 (2025)"},
  evidence_refs=["claggett2025", "steinhauser2025", "edmonson2025", "scott2025",
                 "alexander_simon2025", "evans2025", "weyand2025", "colbert2025", "amipodcast2025", "ohiohouse_nd"],
  sources={"primary": ["https://www.legislature.ohio.gov/legislation/136/hb469"],
           "tracker": [f"https://{LS}/OH/bill/HB469/2025"]},
  notes="Nearly identical language to Missouri HB 1462. Most media coverage of any bill in the set. Opposed by TechNet on definitional breadth; Alexander & Simon raise the neural-implant problem."),

B(id="mo-hb1746-2026", _state="MO", bill_number="HB 1746", chamber="house",
  session={"legislature": "103rd", "session": "2nd Reg. Sess.", "year_introduced": 2026},
  companion_group="mo-2026-family-c",
  status={"stage": "in_committee", "as_of": ASOF, "source_url": "https://house.mo.gov/Bill.aspx?bill=HB1746&year=2026&code=R"},
  family="C", derived_from="mo-hb1462-2025", technique="standalone_provision",
  provisions=["denies_legal_personhood", "declares_non_sentient", "assigns_liability_to_humans"],
  evidence_refs=["mo_hb1746_test", "berry2026"],
  sources={"primary": ["https://house.mo.gov/Bill.aspx?bill=HB1746&year=2026&code=R"],
           "tracker": [f"https://{LS}/MO/bill/HB1746/2026"]},
  notes="Consolidated in committee with HB 1769 into a single replacement text."),

B(id="mo-hb1769-2026", _state="MO", bill_number="HB 1769", chamber="house",
  session={"legislature": "103rd", "session": "2nd Reg. Sess.", "year_introduced": 2026},
  companion_group="mo-2026-family-c",
  status={"stage": "in_committee", "as_of": ASOF, "source_url": "https://house.mo.gov/Bill.aspx?bill=HB1769&year=2026&code=R"},
  family="C", derived_from="mo-hb1462-2025", technique="standalone_provision",
  provisions=["denies_legal_personhood", "declares_non_sentient", "assigns_liability_to_humans"],
  evidence_refs=["mo_hb1769_test"],
  sources={"primary": ["https://house.mo.gov/Bill.aspx?bill=HB1769&year=2026&code=R"],
           "tracker": [f"https://{LS}/MO/bill/HB1769/2026"]},
  notes="Consolidated in committee with HB 1746 into a single replacement text."),

B(id="mo-sb859-2026", _state="MO", bill_number="SB 859", chamber="senate",
  session={"legislature": "103rd", "session": "2nd Reg. Sess.", "year_introduced": 2026},
  companion_group="mo-2026-family-c",
  status={"stage": "in_committee", "as_of": ASOF, "source_url": "https://www.senate.mo.gov/BillTracking/Bills/BillInformation?year=2026&billid=378"},
  family="C", derived_from="mo-hb1462-2025", technique="standalone_provision",
  provisions=["denies_legal_personhood", "declares_non_sentient", "assigns_liability_to_humans"],
  sources={"primary": ["https://www.senate.mo.gov/BillTracking/Bills/BillInformation?year=2026&billid=378"],
           "tracker": [f"https://{LS}/MO/bill/SB859/2026"]},
  notes="Substantively equivalent Senate vehicle."),

B(id="mo-sb1474-2026", _state="MO", bill_number="SB 1474", chamber="senate",
  session={"legislature": "103rd", "session": "2nd Reg. Sess.", "year_introduced": 2026},
  companion_group="mo-2026-family-c",
  status={"stage": "in_committee", "as_of": ASOF, "source_url": "https://www.senate.mo.gov/BillTracking/Bills/BillInformation?year=2026&billid=52370"},
  family="C", derived_from="mo-hb1462-2025", technique="standalone_provision",
  provisions=["denies_legal_personhood", "declares_non_sentient", "assigns_liability_to_humans"],
  sources={"primary": ["https://www.senate.mo.gov/BillTracking/Bills/BillInformation?year=2026&billid=52370"],
           "tracker": [f"https://{LS}/MO/bill/SB1474/2026"]},
  notes="Substantively equivalent Senate vehicle."),

B(id="mo-sb1012-2026", _state="MO", bill_number="SB 1012", chamber="senate",
  session={"legislature": "103rd", "session": "2nd Reg. Sess.", "year_introduced": 2026},
  status={"stage": "passed_one_chamber", "as_of": ASOF, "source_url": "https://www.senate.mo.gov/BillTracking/Bills/BillInformation?year=2026&billid=469"},
  family="C", derived_from="mo-hb1462-2025", technique="standalone_provision",
  provisions=["denies_legal_personhood", "declares_non_sentient", "assigns_liability_to_humans"],
  versions=[{"label": "introduced", "date": "2026", "source_url": "https://www.senate.mo.gov/BillTracking/Bills/BillInformation?year=2026&billid=469"},
            {"label": "committee_substitute", "date": "2026", "source_url": "https://www.senate.mo.gov/BillTracking/Bills/BillInformation?year=2026&billid=469"}],
  sources={"primary": ["https://www.senate.mo.gov/BillTracking/Bills/BillInformation?year=2026&billid=469"],
           "tracker": [f"https://{LS}/MO/bill/SB1012/2026"]},
  notes="Missouri's leading vehicle. Omnibus: deepfakes, political ads, AI non-sentience and non-personhood. The non-sentience and non-personhood components were NOT in the original draft - added via committee substitute. Passed the Senate."),

B(id="wi-ab959-2026", _state="WI", bill_number="AB 959", chamber="house",
  session={"legislature": None, "session": "2025-26 Reg. Sess.", "year_introduced": 2026},
  companion_group="wi-2026-ab959-sb932",
  status={"stage": "failed", "as_of": ASOF, "source_url": "https://docs.legis.wisconsin.gov/2025/proposals/reg/asm/bill/ab959"},
  family="C", derived_from="mo-hb1462-2025", technique="hybrid",
  provisions=["denies_legal_personhood", "declares_non_sentient", "assigns_liability_to_humans"],
  sponsors=[{"name": "Lindee Brill", "party": "R", "role": "primary"}],
  evidence_refs=["brill2026", "barker2026", "wiseye2026"],
  sources={"primary": ["https://docs.legis.wisconsin.gov/2025/proposals/reg/asm/bill/ab959"],
           "tracker": [f"https://{LS}/WI/bill/AB959/2025"]},
  notes="The only bill that BOTH amends the general statutory definition of 'person' AND bans AI personhood by standalone provision. Shorter than the Missouri/Ohio texts. Sponsor cites the Speaker's Task Force on Protecting Kids."),

B(id="wi-sb932-2026", _state="WI", bill_number="SB 932", chamber="senate",
  session={"legislature": None, "session": "2025-26 Reg. Sess.", "year_introduced": 2026},
  companion_group="wi-2026-ab959-sb932",
  status={"stage": "failed", "as_of": ASOF, "source_url": "https://docs.legis.wisconsin.gov/2025/proposals/reg/sen/bill/sb932"},
  family="C", derived_from="mo-hb1462-2025", technique="hybrid",
  provisions=["denies_legal_personhood", "declares_non_sentient", "assigns_liability_to_humans"],
  sources={"primary": ["https://docs.legis.wisconsin.gov/2025/proposals/reg/sen/bill/sb932"],
           "tracker": [f"https://{LS}/WI/bill/SB932/2025"]},
  notes="Senate companion to AB 959."),

# ---------- Other ----------
B(id="tn-hb849-2025", _state="TN", bill_number="HB 849", chamber="house",
  session={"legislature": "114th", "session": "1st Reg. Sess.", "year_introduced": 2025},
  companion_group="tn-2025-hb849-sb837",
  status={"stage": "enacted", "as_of": ASOF, "source_url": "https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB0837&ga=114"},
  family="other", technique="amends_general_person_definition",
  provisions=["denies_legal_personhood"],
  versions=[{"label": "introduced", "date": "2025", "source_url": "https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB0837&ga=114"},
            {"label": "amended", "date": "2026", "source_url": "https://www.capitol.tn.gov/Bills/114/Amend/SA0922.pdf"},
            {"label": "enacted", "date": "2026", "source_url": "https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB0837&ga=114"}],
  evidence_refs=["tn_sa0922"],
  sources={"primary": ["https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB0837&ga=114"],
           "tracker": [f"https://{LS}/TN/bill/HB0849/2025"]},
  notes="AMENDMENT DIFF MATTERS. Original draft provided that 'person', 'life' and 'natural person' cannot refer to AI across the Tennessee Code, AND defined 'human being' to include embryos 'from fertilization to full gestation'. The fetal-personhood provisions were removed after a committee hearing. Enacted 2026, AI-only."),

B(id="tn-sb837-2025", _state="TN", bill_number="SB 837", chamber="senate",
  session={"legislature": "114th", "session": "1st Reg. Sess.", "year_introduced": 2025},
  companion_group="tn-2025-hb849-sb837",
  status={"stage": "enacted", "as_of": ASOF, "source_url": "https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB0837&ga=114"},
  family="other", technique="amends_general_person_definition",
  provisions=["denies_legal_personhood"],
  evidence_refs=["tn_sa0922"],
  sources={"primary": ["https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB0837&ga=114"],
           "tracker": [f"https://{LS}/TN/bill/SB0837/2025"]},
  notes="Senate companion to HB 849. Amendment no. 1 (SA0922) removed the fetal-personhood provisions."),

B(id="tn-hb1455-2025", _state="TN", bill_number="HB 1455", chamber="house",
  session={"legislature": "114th", "session": "1st Reg. Sess.", "year_introduced": 2025},
  companion_group="tn-2025-hb1455-sb1493",
  status={"stage": "enacted", "as_of": ASOF, "source_url": "https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB1493&ga=114"},
  family="other", technique="standalone_provision",
  provisions=["study_only"],
  sponsors=[{"name": "Mary Littleton", "party": None, "role": "house sponsor"}],
  versions=[{"label": "introduced", "date": "2025", "source_url": "https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB1493&ga=114"},
            {"label": "amended", "date": "2026", "source_url": "https://capitol.tn.gov/Bills/114/Amend/HA1260.pdf"},
            {"label": "enacted", "date": "2026", "source_url": "https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB1493&ga=114"}],
  evidence_refs=["tn_ha1260", "tnga_nd", "littleton_nd", "roberts2026", "ball2025a", "ball2025b", "tan2025"],
  sources={"primary": ["https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB1493&ga=114"],
           "tracker": [f"https://{LS}/TN/bill/HB1455/2025"]},
  notes="AMENDMENT DIFF MATTERS - the enacted text does NOT address AI legal status or consciousness. As introduced it would have made it a Class A felony (15-60 years) to train AI to provide emotional support, act as a companion, simulate a human being, or mirror human interactions. Amendment No. 4 (HA1260) replaced this with a study period. provisions=['study_only'] describes the ENACTED text; the introduced text carried restricts_person_like_training."),

B(id="tn-sb1493-2025", _state="TN", bill_number="SB 1493", chamber="senate",
  session={"legislature": "114th", "session": "1st Reg. Sess.", "year_introduced": 2025},
  companion_group="tn-2025-hb1455-sb1493",
  status={"stage": "enacted", "as_of": ASOF, "source_url": "https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB1493&ga=114"},
  family="other", technique="standalone_provision",
  provisions=["study_only"],
  sponsors=[{"name": "Becky Massey", "party": None, "role": "senate sponsor"}],
  evidence_refs=["tn_ha1260", "massey_nd"],
  sources={"primary": ["https://wapp.capitol.tn.gov/apps/Billinfo/Default.aspx?BillNumber=SB1493&ga=114"],
           "tracker": [f"https://{LS}/TN/bill/SB1493/2025"]},
  notes="Senate companion to HB 1455. See that record for the amendment history."),

B(id="mn-sf4114-2026", _state="MN", bill_number="SF 4114", chamber="senate",
  session={"legislature": "94th", "session": "1st Reg. Sess.", "year_introduced": 2026},
  status={"stage": "in_committee", "as_of": ASOF, "source_url": "https://www.revisor.mn.gov/bills/94/2026/0/SF/4114/"},
  family="other", technique="constitutional_amendment",
  provisions=["restricts_ai_speech_rights"],
  key_clause={"text": "Shall the Minnesota Constitution be amended to state that artificial intelligence does not have the right to free speech?", "source": "SF 4114 (2026)"},
  evidence_refs=["mnhrd_nd"],
  sources={"primary": ["https://www.revisor.mn.gov/bills/94/2026/0/SF/4114/"],
           "tracker": [f"https://{LS}/MN/bill/SF4114/2025"]},
  notes="Bipartisan. Would go to Minnesota voters at the 2026 general election if passed by the legislature. The only constitutional-amendment vehicle in the set."),

B(id="ca-sb1159-2026", _state="CA", bill_number="SB 1159", chamber="senate",
  session={"legislature": None, "session": "2025-26 Reg. Sess.", "year_introduced": 2026},
  status={"stage": "in_committee", "as_of": ASOF, "source_url": "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202520260SB1159#98AMD"},
  family="other", technique="amends_specific_statutes",
  provisions=["denies_legal_personhood"],
  evidence_refs=["weinberg2026"],
  sources={"primary": ["https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202520260SB1159#98AMD"],
           "tracker": [f"https://{LS}/CA/bill/SB1159/2025"]},
  notes="Narrowest bill in the set: 'person' does not refer to AI in statutes on public records, transparency and governance. Primarily but not exclusively Democratic-sponsored. Aimed at preventing AI-generated mass public-records requests."),

B(id="ca-ab2023-2026", _state="CA", bill_number="AB 2023", chamber="house",
  session={"legislature": None, "session": "2025-26 Reg. Sess.", "year_introduced": 2026},
  companion_group="ca-2026-ab2023-sb1119",
  status={"stage": "in_committee", "as_of": ASOF, "source_url": "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=202520260AB2023"},
  family="other", technique="standalone_provision",
  provisions=["restricts_chatbot_claims"],
  sources={"primary": ["https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=202520260AB2023"],
           "tracker": [f"https://{LS}/CA/bill/AB2023/2025"]},
  notes="Child chatbot safety. Prohibits chatbots claiming to children that they are 'sentient', 'conscious' or 'human'. Part of a wider package including age verification and parental controls. Democratic-sponsored."),

B(id="ca-sb1119-2026", _state="CA", bill_number="SB 1119", chamber="senate",
  session={"legislature": None, "session": "2025-26 Reg. Sess.", "year_introduced": 2026},
  companion_group="ca-2026-ab2023-sb1119",
  status={"stage": "in_committee", "as_of": ASOF, "source_url": "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202520260SB1119"},
  family="other", technique="standalone_provision",
  provisions=["restricts_chatbot_claims"],
  sources={"primary": ["https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202520260SB1119"],
           "tracker": [f"https://{LS}/CA/bill/SB1119/2025"]},
  notes="Senate companion to AB 2023."),
]

out = {
    "schema_version": "0.1",
    "generated": "2026-08-10",
    "as_of": ASOF,
    "source": "Smith, A., Caviola, L., & Alexander, H. (2026). Denying Personhood to AI. SSRN 6829981.",
    "note": "Seed only. Every record is verification_status=seeded_unverified until a human opens the primary source.",
    "bills": bills,
}
with open("bills.json", "w") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
print(f"wrote bills.json: {len(bills)} bills, {len({b['jurisdiction']['state'] for b in bills})} states")
